var idTutoria=0,idUsuario=0,tipoDeUsuario="alumno",idEtapa=-1,etapas="cero;uno;dos;tres;B\u00fasqueda De Observadores;Demostraci\u00f3n;Aprobado".split(";"),autorizacion=1,mensaje="",idUltimoMensaje=0,hayPeticionAjax=!1,cancelarPeticion=!1,DEMOSTRACION=5,BUSQUEDA_DE_SINODALES=4,TEMPO_CHAT=0,TEMPO_SUBIR_ARCHIVO=1,INTERVALO_CHAT=3E3,INTERVALO_SUBIR_ARCHIVO=2500,tempoChat,tempoSubirArchivo,winSubir=null,winSubirArchivo=null,nombreDelArchivo="",urlDelArchivo="",esUrl=!1,numeroDeBoton=0,numeroDeProductos=
0,player="",rutaDelAudio="lib/audio/mensaje_nuevo";descargaMensajesPrevios=function(){$.ajax({type:"POST",url:"lib/php/mensajesPrevios.php",data:{idTutoria:idTutoria,tipoDeUsuario:tipoDeUsuario},dataType:"xml",success:actualizaConversacion,error:error})};
actualizaConversacion=function(a){idUltimoMensaje=parseInt($(a).find("idUltimoMensaje").text());var b=$(a).find("mensajes").children(),d=$(a).find("pendientes").children();mensaje="";b.each(function(){var a=$("#ventanaDeConversacion"),b=a.html(),c;c=""+('<span class="fecha">'+$(this).attr("fecha")+"</span><br/>");c=c+'<div class="sbl"><div class="sbr"><div class="stl"><div class="str">'+('<span class="mensaje">'+$(this).text()+"</span>");c+='</div></div></div></div><div class="sb">';c+='<img class="character" src="../../avatares/'+
$(this).attr("idUsuario")+'.jpg"/>';c+='<b class="nick">';c+=$(this).attr("nick")+"</b>";a.html(b+c);autoScroll("ventanaDeConversacion")});d.each(function(){var a="",a='<div class="itemlist"><img class="boton" src="../../lib/img/ok2.png"/>'+('<p value="'+$(this).attr("idUsuario")+","+$(this).attr("idMensaje")+'">'),a=a+($(this).attr("fecha")+"<br/>"),a=a+("De: "+$(this).attr("nick")+"<br/>"),a=a+"<span>x </span>",a=a+"</p><br/>",a=a+"</div>";$("#pendientes").html($("#pendientes").html()+a);$("#pendientes").find("img").click(function(){var a=
$(this).siblings("p"),b=a.attr("value").split(",");$(this).parent().load("lib/php/autorizarMensaje.php",{idTutoria:idTutoria,idUsuario:b[0],idMensaje:b[1],idEtapa:DEMOSTRACION,mensaje:a.children("span").html()});$(this).parent().hide()})});0!=b.length&&"on"==$("#sonidoOnOff").attr("value")&&$("#sonido").html(player);idEtapa=parseInt($(a).find("ultimaEtapa").text());$("#etapa").text(etapas[idEtapa]);switch(idEtapa){case DEMOSTRACION:"moderador"!=tipoDeUsuario&&("demostrador"!=tipoDeUsuario&&"sinodal"!=
tipoDeUsuario&&"observador"!=tipoDeUsuario)&&cambiaADemostracion();case BUSQUEDA_DE_SINODALES:$("#buscaSinodales").show()}a=parseInt($(a).find("productosNuevos").text());a!=numeroDeProductos&&(numeroDeProductos=a,actualizaListaDeProductos());window.clearInterval(tempoChat);tempoChat=window.setInterval(descargaMensajesNuevos,INTERVALO_CHAT)};
descargaMensajesNuevos=function(){window.clearInterval(tempoChat);$.ajax({type:"POST",url:"lib/php/chat.php",data:{idTutoria:idTutoria,mensaje:mensaje,idUltimoMensaje:idUltimoMensaje,idEtapa:idEtapa,tipoDeUsuario:tipoDeUsuario,numeroDeProductos:numeroDeProductos},dataType:"xml",success:actualizaConversacion,error:error})};
inicializaChat=function(){$("#mensaje").val("");$("#mensaje").keyup(function(a){var b=$("#mensaje"),d=255-b.val().length;13==a.which&&!a.shiftKey&&(a.preventDefault(),$("#enviarMensaje").click(),$("#caracteresRestantes").html(b.attr("maxLength")));255<b.val().length&&($("#mensaje").val(b.val().substr(0,255)),d=0);$("#caracteresRestantes").html(d)});$("#enviarMensaje").click(function(){mensaje=$("#mensaje").val().trim();255<mensaje.lenght&&(mensaje=mensaje.substr(0,254));$("#mensaje").val("");$("#caracteresRestantes").html(255);
descargaMensajesNuevos()});$("#enviarArchivo").click(function(){var a;a="directories=no,height=150px,width=500px,location=no,menubar=no,resizable=no,titlebar=no,toolbar=no";var b="subirArchivo.html?idUsuario="+idUsuario+"&",b=b+("&crp=chat&idTutoria="+idTutoria);winSubirArchivo=window.open(b,"SubirArchivo",a);window.clearInterval(tempoSubirArchivo);tempoSubirArchivo=window.setInterval(function(){winSubirArchivo.closed&&""!=urlDelArchivo&&(window.clearInterval(tempoSubirArchivo),mensaje='<a href="'+
urlDelArchivo+'" target="_blank">',mensaje+=urlDelArchivo+"</a>",urlDelArchivo=nombreDelArchivo="",$("#mensaje").attr("value",mensaje),$("#enviarMensaje").click())},INTERVALO_SUBIR_ARCHIVO)});$("#sonidoOnOff").click(function(){var a="on";"off"==$(this).attr("value")?(a="on",$("#sonido").html(player)):a="off";$(this).attr("src","../../lib/img/sonido"+a+".png").attr("value",a).attr("alt","Sonido: "+a)})};
inicializaRecursos=function(){actualizaListaDeRecursos();$("#subirRecurso").click(function(){var a;a="directories=no,height=150px,width=500px,location=no,menubar=yes,resizable=no,titlebar=yes,toolbar=yes";winSubirRecurso=window.open("subirArchivo.html"+("?idUsuario="+idUsuario+"&crp=recursos&idTutoria="+idTutoria),"SubirArchivo",a);window.clearInterval(tempoSubirArchivo);tempoSubirArchivo=window.setInterval(function(){winSubirRecurso.closed&&(window.clearInterval(tempoSubirArchivo),actualizaListaDeRecursos())},
INTERVALO_SUBIR_ARCHIVO)})};
actualizaListaDeRecursos=function(){$.ajax({type:"post",url:"lib/php/listaDeProductosORecursos.php",data:{r:"si",idTutoria:idTutoria},dataType:"html",success:function(a){$("#listaDeRecursos").html(a);a=$("#recursos");a.find("span").click(function(){var a=$(this),d=-1==a.html().indexOf("http://")?!1:!0,e=a.html(),f=a.attr("value"),a=a.attr("alt");tipo=d?"direccion":"archivo";mensaje="Por favor revisa el siguiente "+tipo+': <a href="'+f+'" target="_blank" alt="'+a+'">'+e+"</a>";$("#mensaje").val(mensaje);
$("#enviarMensaje").click()});a.find("img").click(function(){var a=$(this).siblings().attr("value");$.ajax({type:"POST",url:"lib/php/borraArchivo.php",context:this,dataType:"text",data:{tipo:"recurso",url:a},success:function(a){"exito"==a?$(this).parent().hide("slow"):error(a)},error:error})})},error:error})};
actualizaListaDeProductos=function(){$.ajax({type:"POST",url:"lib/php/listaDeProductosORecursos.php",dataType:"html",data:{idTutoria:idTutoria},success:function(a){$("#listaDeProductos").html(a);a=$("#productos");a.find("span").click(function(){var a=$(this),d=a.html(),e=a.attr("value"),a=a.attr("alt");mensaje='Por favor revisa el siguiente archivo: <a href="'+e+'" target="_blank" alt="'+a+'" title="'+a+'">'+d+"</a>";$("#mensaje").val(mensaje);$("#enviarMensaje").click()});a.find("img").click(function(){url=
$(this).siblings().attr("value");$.ajax({type:"POST",url:"lib/php/borraArchivo.php",context:this,dataType:"text",data:{tipo:"producto",url:url},success:function(a){"exito"==a?$(this).parent().hide("slow"):error(a)},error:error})})},error:error})};
inicializaProductos=function(){actualizaListaDeProductos();$("#subirProductos button").click(function(){var a=$(this).attr("value"),b;b="directories=no,height=150px,width=500px,location=no,menubar=yes,resizable=no,titlebar=no,toolbar=no";var d="subirArchivo.html?idTutoria="+idTutoria+"&crp=productos";winSubirArchivo=window.open(d+("&idBoton="+a),"SubirArchivo",b)})};
cambiaADemostracion=function(){window.clearInterval(tempoChat);window.clearInterval(tempoSubirArchivo);var a;switch(tipoDeUsuario){case "tutor":tipoDeUsuario="moderador";break;case "alumno":tipoDeUsuario="demostrador";break;case "observador":tipoDeUsuario="sinodal"}a="tutoria.php?"+("idUsuario="+idUsuario+"&");a+="tipoDeUsuario="+tipoDeUsuario+"&";a+="idTutoria="+idTutoria;window.location=a};
buscaSinodales=function(){$.ajax({type:"POST",url:"lib/php/buscaSinodales.php",data:{idTutoria:idTutoria},error:error})};agregaTemaDeCatalogo=function(a){$.ajax({url:"lib/php/agregarTemaDeCatalogo.php",data:{idTutoria:idTutoria,nombre:a},type:"POST",typeData:"text",success:function(a){$("#temaCaptura").children("input").val("");alert(a);$("#a\u00f1adirTemasDeCatalogo").children("button").click()}})};
inicializaAgregarTemaDeCatalogo=function(){$("#a\u00f1adirTemaDeCatalogo").show("slow");$("#a\u00f1adirTemaDeCatalogo").click(function(){$("#temaCaptura").toggle("slow")});$("#temaCaptura").hide();$("#temaCaptura").children("button").prop("disabled",!0);$("#temaCaptura").children("button").click(function(){var a=$("#temaCaptura").children("input").val();confirm("Una vez agregado el tema no podra ser borrado.\n\u00bfEstas seguro que quieres guardar el tema con el nombre "+a+"?")&&agregaTemaDeCatalogo(a)});
$("#temaCaptura input").keyup(function(){""!=$(this).val()?$(this).siblings("button").prop("disabled",!1):$(this).siblings("button").prop("disabled",!0)})};
$(document).ready(function(){tipoDeUsuario=getUrlVars().tipoDeUsuario;idTutoria=getUrlVars().idTutoria;idUsuario=dameIdUsuario();var a;a='<audio controls preload="auto" autobuffer autoplay="autoplay">'+('<source src="'+rutaDelAudio+'.ogg" type="audio/ogg"/>');a+='<source src="'+rutaDelAudio+'.mp3" type="audio/mpeg"/>';a+="\u00ac\u00ac tu navegador no soprota html. \u00bfporque no se cargo el flash?</audio>";var b;b='<object type="application/x-shockwave-flash" data="lib/flash/dewplayer-mini.swf" width="0" height="0" id="dewplayermini" name="dewplayermini">';
b+='<param name="movie" value="lib/flash/dewplayer-mini.swf" />';b+='<param name="flashvars" value="mp3='+rutaDelAudio+'.mp3&amp;autostart=1" /></object>';Modernizr.audio?(player=a,$("#sonido").hide()):player=b;descargaMensajesPrevios();inicializaChat();switch(tipoDeUsuario){case "tutor":inicializaRecursos();inicializaProductos();inicializaAgregarTemaDeCatalogo();$("#siguienteEtapa").click(function(){idEtapa++;switch(idEtapa){case DEMOSTRACION:$("#mensaje").val("En la Etapa de Demostraci\u00f3n");
break;case BUSQUEDA_DE_SINODALES:buscaSinodales();$("#mensaje").val("Etapa: "+etapas[idEtapa]);break;default:$("#mensaje").val("Etapa: "+etapas[idEtapa])}$("#enviarMensaje").click()});$("#buscaSinodales").click(function(){buscaSinodales();$("#mensaje").val("Buscando Observadores...");$("#enviarMensaje").click()}).hide();break;case "moderador":$("#a\u00f1adirTemaDeCatalogo").hide();$("#aprobar").click(function(){agregaTemaDeCatalogo(dameNombreDelTema(idTutoria));$.ajax({url:"lib/php/aprobar.php",type:"POST",
data:{idTutoria:idTutoria},typeData:"text",success:function(){idEtapa=6;$("#mensaje").val("\u00a1Demostraci\u00f3n Aprobada!\u00a1Felicidades! Ahora ya puedes tutorar.");$("#enviarMensaje").click()},error:error})});break;case "observador":$("#enviarMensaje").prop("disabled",!0);$("#mensaje").prop("disabled",!0);$("#enviarArchivo").prop("disabled",!0);break;case "sinodal":autorizacion=0;break;case "alumno":idEtapa==DEMOSTRACION?cambiaADemostracion():inicializaProductos()}window.clearInterval(tempoChat);
tempoChat=window.setInterval(descargaMensajesNuevos,INTERVALO_CHAT)});