var idsTemas=0,idTema=0,idTutor=0,idUsuario=0,numeroDePagina=0,asunto="Solicitud de Tutor\u00eda",mensaje="",nombreDelTutor="",nombreDelTema="",nombreDelAlumno="";
$(document).ready(function(){idUsuario=dameIdUsuario();nombreDelAlumno=dameNombreDeUsuario();$("#lista2,#lista3,#lista4").hide();$("#enviarSolicitud button").prop("disabled",!0);$("#enviarSolicitud button").click(function(){$("#lista2,#lista3,#lista4").hide("slow");$("#lista2 select").unbind("change");$("#lista3 select").unbind("change");$("#lista4 select").unbind("change");$(this).prop("disabled",!0);mensaje+="<h1>Solicitud de tutoria</h1>";mensaje+="<p> Hola <b>"+nombreDelTutor+"</b></p>";mensaje+=
"<p>\u00bfTe gustar\u00eda ser tutor de "+nombreDelAlumno+" en el tema: ";mensaje+="<b>"+nombreDelTema+"</b>?</p>";mensaje+="<p>Si la respuesta es afirmativa, has click:";mensaje+='<a href="';mensaje+="../../modulos/solicitudDeTutoria/creaTutoria.php?idTema=";mensaje+=idTema+"&idTutorado="+idUsuario+'">';mensaje+="Aceptar Tutoria</a> </p>";mensaje+="<p>En caso contrario da click en: ";mensaje+="<a href=";mensaje+="../../modulos/solicitudDeTutoria/rechasaTutoria.php?";mensaje+="de="+idTutor;mensaje+=
"&from="+idUsuario;mensaje+="&nombreDelTutor="+encodeURIComponent(nombreDelTutor);mensaje+="&nombreDelTema="+encodeURIComponent(nombreDelTema);mensaje+=">";mensaje+="No aceptar</a>";mensaje+="</p>";$.ajax({type:"POST",url:"../../modulos/mensajesPrivados/mensajesPrivados.php",typeData:"xml",data:{accion:"guarda",de:idUsuario,para:idTutor,asunto:asunto,mensaje:mensaje},success:function(){$("#m").html("Solicitud enviada a <b>"+nombreDelTutor+"</b> del tema <b>"+nombreDelTema+"</b>");mensaje=""}})});
buscaComponenteEjeCategoria()});buscaTemasPorNombre=function(){$.ajax({type:"POST",url:"listaDeTemasPorNombre.php",typeData:"html",success:function(a){$("#lista1 select").html(a);$("#lista1 select").change(function(){var a=$("#lista1 select>option:selected");$("#enviarSolicitud button").prop("disabled",!0);idsTemas=$(this).val();nombreDelTema=a.text();buscaTutoresPorTema(idsTemas,nombreDelTema)})},error:error})};
buscaTutoresPorNick=function(){$.ajax({type:"POST",url:"listaDeTutores.php",typeData:"html",success:function(a){$("#lista1 select").html(a);$("#lista1 select").change(function(){var a=$("#lista1 select>option:selected");$("#enviarSolicitud button").prop("disabled",!0);idTutor=$(this).val();nombreDelTutor=a.text();buscaTemasPorTutor(idTutor)})},error:error})};
buscaTutoresPorTema=function(a){$("#lista4").children("select").load("lib/php/listaDeTutoresPorNombreDeTema.php",{idsTemas:a},function(){$("#lista4").children("select").change(function(){var a=$(this).attr("value").split(",");idTema=a[0];idTutor=a[1];nombreDelTutor=$(this).children("option:selected").text();$("#enviarSolicitud button").prop("disabled",!1)})})};
buscaTemasPorTutor=function(){$.ajax({type:"POST",url:"listaDeTemasPorTutor.php",typeData:"html",data:{idTutor:idTutor},success:function(a){$("#lista2 select").html(a);$("#lista2 select").change(function(){nombreDelTema=$("#lista2 select>option:selected").text();idTema=$(this).val();$("#enviarSolicitud button").prop("disabled",!1)});$("#lista2").show("slow")},error:error})};
buscaComponenteEjeCategoria=function(){$("#lista1").children("select").load("lib/php/listaDeComponenteEjeCategoria.php",{},function(){$("#lista1").children("select").change(function(){$("#enviarSolicitud").children("button").prop("disabled",!0);$("#lista3,#lista4").hide("slow");buscaEstandaresPorCEC($(this).val());$("#lista2").show("slow")})})};
buscaEstandaresPorCEC=function(a){$("#lista2").children("select").load("lib/php/listaDeEstandaresPorCEC.php",{idCEC:a},function(){$("#lista2").children("select").change(function(){$("#lista4").hide("slow");$("#enviarSolicitud button").prop("disabled",!0);buscaTemasPorEstandar($(this).val());$("#lista3").show("slow")})})};
buscaTemasPorEstandar=function(a){$("#lista3").children("select").load("lib/php/listaDeTemasPorEstandar.php",{idEstandar:a},function(){$("#lista3").children("select").change(function(){nombreDelTema=$(this).children("option:selected").text();$("#enviarSolicitud button").prop("disabled",!0);buscaTutoresPorTema($(this).val());$("#lista4").show("slow")})})};